name: Add Tags to PR

on:
  pull_request:
    paths:
      - 'public/data/**'

jobs:
  add-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for data changes
        id: data-check
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

          # Check if specific files are modified
          if echo "$CHANGED_FILES" | grep -qE 'public/data/**'; thegit 
            echo "Folder changed: $CHANGED_FILES"
            echo "::set-output name=tag_triggered::true"
          else
            echo "No relevant files changed. Skipping tag."
            echo "::set-output name=tag_triggered::false"
          fi

      - name: Add tag to PR if files changed
        if: steps.data-check.outputs.tag_triggered == 'true'
        run: |
          git push origin data-change
